kind: Service
apiVersion: v1
metadata:
  name: eagleproxy-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 80
    nodePort: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eagleproxy-deployment
  labels:
    app: eagleproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eagleproxy
      track: stable
  template:
    metadata:
      labels:
        app: eagleproxy
        track: stable
    spec:
      containers:
      - name: eagleproxy
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
